### PR TITLE
As seen on TV

### PR DESCRIPTION
**Pull request by modi95**

### CODE REVIEW

**Comment by minimaxir** [comment]
-1

You are using spaces to indent. That's terrible. You're terrible.

**Comment by modi95** [comment]
Hey, I'm just following some else's style guide here 😆

**Comment by lewismoten** [comment]
You need to follow the companies style guide. The least you can do is to use a linter to catch the problems.

**Comment by opello** [comment]
The code shown was a modified version of [tensorflow/tensorflow's tensorflow/stream_executor/stream.cc](https://github.com/tensorflow/tensorflow/blob/9c3043ff3bf31a6a81810b4ce9e87ef936f1f529/tensorflow/stream_executor/stream.cc#L31).

And as shown the [Stitchpunk/atari-ai](https://github.com/Stitchpunk/atari-ai/) was forked from [codeopalmo](https://github.com/codeopalmo)/atari-ai but that is either private or nonexistent.

**Comment by YashalKanungo** [comment]
This is proprietary software owned by www.hooli.com

This letter is notification under Section 420(xyz) of the Digital Millennium Copyright Act (”DMCA”), and we seek the removal of the aforementioned infringing material from your servers. We request that you immediately notify the infringer of this notice and inform them of their duty to remove the infringing material immediately, and notify them to cease any further posting of infringing material to your server in the future.

Our algorithm has also tracked that the employees at www.piedpiper.com did aid and abet the concerned person.

**Pull request merged**
