### PR TITLE
Added contributing note

### PR DESCRIPTION
**Pull request by lewismoten**
4 spaces are better than tabs as they give us more precision, and it doesn't matter to the compiler either way.

### CODE REVIEW

**Comment by minimaxir** [comment]
This is blasphemy. This is madness!

**Comment by lewismoten** [comment]
@minimaxir, you are not adding any substantial basis to your argument Please provide a recommendation with subsistence.

**Comment by lumenwrites** [comment]
Spaces make more sense. Also emacs automatically indents everything correctly, so you really do _not_ need to type space 4 times, come on.

Not that I care, I'm not a nazi.

**Comment by lewismoten** [comment]
I don't always hit the space key, but when I do, I space out.

**Pull request merged**
