### PR TITLE
Replace all spaces with poop emoji

### PR DESCRIPTION
**Pull request by BenSjoberg**
As in literally all of them.

This is the next big software design pattern and I think it would serve this project well.

### CODE REVIEW

**Comment by Stitchpunk** [comment]
Please please pull and update PR

**Comment by BenSjoberg** [comment]
Done.

**Comment by dalyhabit** [comment]
This was so unnecessary. And FYI you broke the README. @BenSjoberg

**Comment by BenSjoberg** [comment]
I...did not expect this to be accepted. Sorry. D:

Edit: But also kind of not sorry.

**Comment by dalyhabit** [comment]
Alright it was kinda funny

Edit: But now the whole repo is 💩 'ed. And there was at least some attempt at real code in here on Sunday lol.

**Pull request merged**
