### PR TITLE
Provide initial CONTRIBUTORS file

### PR DESCRIPTION
**Pull request by leee**
I've already gone ahead and squashed my commits, and I believe this pull request conforms to the code of conduct and contribution guidelines.

Please let me know if you'd like for me to submit a patch instead.

### CODE REVIEW

**Comment by phuvp** [comment]
CR: LGTM. +2, this should be merged immediately.

**Comment by dalyhabit** [comment]
The poop emoji guy doesn't deserve to be on this list

**Comment by leee** [comment]
@dalyhabit if you point out the offending line I'd be glad to update my pull request.

**Comment by dalyhabit** [comment]
@leee I didn't reply quick enough, so I opened a new PR with the edit lol

**Comment by leee** [comment]
@dalyhabit Reasonable.

**Pull request merged**
